#acatism_authentication_homepage:
#    pattern:  /login/{name}
#    defaults: { _controller: AcatismAuthenticationBundle:Default:index }

acatism_success:
     pattern: /success
     defaults: { _controller: AcatismMainBundle:Success:success }


