# src/Acatism/AuthenticationBundle/Resources/config/validation.yml

Acatism\AuthenticationBundle\Document\User:
      constraints:
           - Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique: 
                    fields: email
                    message: 'This e-mail is already in use'
           - Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique: 
                    fields: username
                    message: 'This username is already in use'
      properties:
           email:
              - Regex:
                   pattern: "/^[a-zA-Z]+[.][a-zA-Z]+[@info.uaic.ro]/"
                   message: 'Your e-mail must match this pattern: firstname.lastname@info.uaic.ro'

