acatism_main_homepage:
    pattern:  /
    defaults: { _controller: AcatismMainBundle:Default:index }

acatism_new_project:
    pattern: /new_project
    defaults: { _controller: AcatismMainBundle:Creation:newProject }

acatism_new_task:
    pattern: /new_task
    defaults: { _controller: AcatismMainBundle:Creation:newTask }

acatism_success:
    pattern: /success
    defaults: { _controller: AcatismMainBundle:Success:success }

acatism_delete_project:
    pattern: /delete_project/{project_id}
    defaults: { _controller: AcatismMainBundle:Delete:deleteProject }

acatism_delete_task:
    pattern: /delete_task/{task_id}
    defaults: { _controller: AcatismMainBundle:Delete:deleteTask }

acatism_view_students:
    pattern: /students/
    defaults: { _controller: AcatismMainBundle:View:viewAllStudents }

acatism_view_student:
    pattern: /students/{username}
    defaults: { _controller: AcatismMainBundle:View:viewStudent}

acatism_view_profs:
    pattern: /profs/
    defaults: { _controller: AcatismMainBundle:View:viewAllProfs }

acatism_view_prof:
    pattern: /profs/{username}
    defaults: { _controller: AcatismMainBundle:View:viewProf}

acatism_new_application:
    pattern: /new_application/{proj_id}
    defaults: { _controller: AcatismMainBundle:Creation:newApplication }

acatism_cancel_application:
    pattern: /cancel_application/{proj_id}
    defaults: { _controller: AcatismMainBundle:Delete:cancelApplication }


