acatism_main_homepage:
    pattern:  /
    defaults: { _controller: AcatismMainBundle:Default:index }

acatism_profile_settings:
    pattern:  /settings
    defaults: { _controller: AcatismMainBundle:Default:profileSettings }

acatism_new_project:
    pattern: /new_project
    defaults: { _controller: AcatismMainBundle:Creation:newProject }

acatism_new_task:
    pattern: /new_task
    defaults: { _controller: AcatismMainBundle:Creation:newTask }

acatism_new_post:
    pattern: /new_post
    defaults: { _controller: AcatismMainBundle:Creation:newPost }

acatism_delete_project:
    pattern: /delete_project/{project_id}
    defaults: { _controller: AcatismMainBundle:Delete:deleteProject }

acatism_delete_task:
    pattern: /delete_task/{task_id}
    defaults: { _controller: AcatismMainBundle:Delete:deleteTask }

acatism_delete_post:
    pattern: /delete_post/{post_id}
    defaults: { _controller: AcatismMainBundle:Delete:deletePost }

acatism_view_students:
    pattern: /students/
    defaults: { _controller: AcatismMainBundle:View:viewAllStudents }

acatism_view_student:
    pattern: /students/{username}
    defaults: { _controller: AcatismMainBundle:View:viewStudent}

acatism_view_profs:
    pattern: /profs/
    defaults: { _controller: AcatismMainBundle:View:viewAllProfs }

acatism_view_prof:
    pattern: /profs/{username}
    defaults: { _controller: AcatismMainBundle:View:viewProf}

acatism_new_application:
    pattern: /new_application/{proj_id}
    defaults: { _controller: AcatismMainBundle:Creation:newApplication }

acatism_cancel_application:
    pattern: /cancel_application/{proj_id}
    defaults: { _controller: AcatismMainBundle:Delete:cancelApplication }

acatism_accept_application:
    pattern: /accept_application/{applicationId}
    defaults: { _controller: AcatismMainBundle:Application:accept }

acatism_decline_application:
    pattern: /decline_application/{applicationId}
    defaults: { _controller: AcatismMainBundle:Application:decline }

acatism_confirm_application:
    pattern: /confirm_application/{applicationId}
    defaults: { _controller: AcatismMainBundle:Application:confirm }

acatism_news_feed:
    pattern: /newsfeed
    defaults: { _controller: AcatismMainBundle:Default:newsFeed }

acatism_update_social_links:
    pattern: /update_social
    defaults: { _controller: AcatismMainBundle:Default:profileSettings }

acatism_search:
    pattern: /search/{keywords}
    defaults: { _controller: AcatismMainBundle:View:search }

email_template:
    pattern: /email_template
    defaults: { _controller: AcatismMainBundle:View:email }

about:
    pattern: /about
    defaults: { _controller: AcatismMainBundle:Info:about }

userguide:
    pattern: /userguide
    defaults: { _controller: AcatismMainBundle:Info:userguide}
