parameters:
#    acatism_main.example.class: Acatism\MainBundle\Example

services:
#    acatism_main.example:
#        class: %acatism_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
