# src/Acatism/MainBundle/Resources/config/validation.yml

Acatism\MainBundle\Document\Project:
    properties:
        name:
            - NotBlank: ~

        description:
            - Length:
                 min: 200
                 minMessage: "Project description must be at least 200 chars length ! "

