# src/Acatism/MainBundle/Resources/config/validation.yml

Acatism\MainBundle\Document\Project:
    properties:
        name:
            - NotBlank: ~
        description:
            - NotBlank: ~


Acatism\MainBundle\Document\Task:
    properties:
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~

Acatism\MainBundle\Document\Post:
    properties:
        title:
            - NotBlank: ~
        content:
            - NotBlank: ~


Acatism\MainBundle\Document\Person:
    properties:
        cvFile:
            - File:
                maxSize: 4096k
                mimeTypes: [application/pdf, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.oasis.opendocument.text]
       
        profileFile:
            - File:
                maxSize: 4096k
                mimeTypes: [image/*]

Acatism\MainBundle\Document\SocialMedia:
    properties:
        facebook:
            - Url: ~
        googleplus:
            - Url: ~
        twitter:
            - Url: ~
        skype:
            - Url: ~
        dropbox:
            - Url: ~
        github:
            - Url: ~

